// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package rdm

import (
	"time"
)

const TableNameSchedulerLocker = "scheduler_locker"

// SchedulerLocker 调度 locker 存储
type SchedulerLocker struct {
	ID         int64     `gorm:"column:id;primaryKey;comment:主键" json:"id"`                                           // 主键
	Key        string    `gorm:"column:key;not null;comment:存储的 key" json:"key"`                                      // 存储的 key
	InstanceID int64     `gorm:"column:instance_id;not null;comment:instance 主键" json:"instance_id"`                  // instance 主键
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt  time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName SchedulerLocker's table name
func (*SchedulerLocker) TableName() string {
	return TableNameSchedulerLocker
}
